development: &development
  adapter: postgresql
  encoding: unicode
  database: DoGood-app_development
  host: localhost
  pool: 5
  username: mhayman

test:
  adapter: postgresql
  encoding: unicode
  database: DoGood-app_test
  pool: 5
  username: mhayman

production:
  <<: *development

